# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilitadoarbitrar',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
