# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20161206_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilitadoarbitrar',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
